---

- name: Remove existing keystore passwords
  command:
    docker exec elasticsearch /usr/share/elasticsearch/bin/elasticsearch-keystore remove "{{ _elasticsearch__passname }}"
  register: result
  failed_when:
    - result is failed
    - result.stderr is not search('does not exist in the keystore')
  when: elastic_certificates_password_renew | bool
  loop:
    - xpack.security.transport.ssl.secure_key_passphrase
    - xpack.security.http.ssl.secure_key_passphrase
  loop_control:
    loop_var: _elasticsearch__passname


- name: List keystore settings
  command: docker exec elasticsearch /usr/share/elasticsearch/bin/elasticsearch-keystore list
  register: _elastic_keystore_settings
  changed_when: false


- name: Add certificates password to elastic keystore
  shell: echo '{{ elastic_certificates_password }}' | docker exec -i elasticsearch /usr/share/elasticsearch/bin/elasticsearch-keystore add "{{ _elasticsearch__passname }}" --stdin
  when: >-
    _elastic_keystore_settings.stdout is not search(_elasticsearch__passname)
  loop:
    - xpack.security.transport.ssl.secure_key_passphrase
    - xpack.security.http.ssl.secure_key_passphrase
  loop_control:
    loop_var: _elasticsearch__passname
  changed_when: false
  no_log: >-
    {{
      lookup('env', 'IN_MOLECULE')
      | default(false, true)
      | ternary(false, true)
    }}