---

- name: Check if a keystore exists
  command: docker exec kibana test -f /usr/share/kibana/config/kibana.keystore
  register: result
  ignore_errors: true
  changed_when: false


- name: Create kibana keystore
  command: docker exec kibana /usr/share/kibana/bin/kibana-keystore create
  when: result.rc != 0
