---

- name: "{{ beats_flavor }}: Check if a keystore exists on Linux"
  stat:
    path: "{{ beats_path_data }}/{{ beats_flavor }}.keystore"
  register: result


- name: Create keystore
  command: "docker exec {{ beats_flavor }} {{ beats_linux_exec }} keystore create"
  when: not result.stat.exists | bool