---

- name: Check if a keystore exists
  command: "docker exec {{ beats_flavor }} test -f /usr/share/{{ beats_flavor }}/data/{{ beats_flavor }}.keystore"
  register: result
  ignore_errors: true
  changed_when: false


- name: Create keystore
  command: "docker exec {{ beats_flavor }} {{ beats_flavor }} 
      --path.data /usr/share/{{ beats_flavor }}/data 
      --path.config /usr/share/{{ beats_flavor }} 
      --path.home {{ beats_path_home }} 
      --path.logs /usr/share/{{ beats_flavor }}/logs keystore create"
  when: result.rc != 0

