---

- name: "{{ beats_flavor }}: keystore tasks for Linux"
  block:
  - name: "{{ beats_flavor }}: Check if a keystore exists on Linux"
    stat:
      path: "{{ beats_path_data }}/{{ beats_flavor }}.keystore"
    register: result

  - name: "{{ beats_flavor }}: Create keystore on Linux"
    command: "docker exec {{ beats_flavor }} {{ beats_linux_exec }} keystore create"
    when: not result.stat.exists | bool
  when: ansible_os_family != 'Windows'


- name: "{{ beats_flavor }}: keystore tasks for Windows"
  block:
    - name: "{{ beats_flavor }}: Check if a keystore exists on Windows"
      win_stat:
        path: "{{ beats_path_data }}/{{ beats_flavor }}.keystore"
      register: result

    - name: "{{ beats_flavor }}: Create keystore on Windows"
      win_command: "{{ beats_win_exec }} keystore create"
      when: not result.stat.exists | bool
  when: ansible_os_family == 'Windows'