---
- name: "{{ beats_flavor }}: Get version"
  command: "docker exec {{ beats_flavor }} {{ beats_linux_exec }} version"
  register: _beats_version_output
  changed_when: false

- name: "{{ beats_flavor }}: Register beats version"
  set_fact:
    beats_full_version: "{{ _beats_version_output.stdout.split(' ')[2] | replace(',', '') }}"
