---

name: CI

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "5 5 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - image: jrei/systemd-ubuntu:20.04
            instance: systemd-ubuntu-20.04
         # - image: jrei/systemd-ubuntu:22.04
        #    instance: systemd-ubuntu-22.04
            # - image: jrei/systemd-centos:7
            #   instance: systemd-centos-7
            # - image: jrei/systemd-centos:8
            #   instance: systemd-centos-8
            # - image: jrei/systemd-debian:9
            #   instance: systemd-debian-9
            # - image: jrei/systemd-debian:10
            #   instance: systemd-debian-10
        beats_flavor:
          - auditbeat
          #- filebeat
          #- heartbeat
          #- journalbeat
          #- metricbeat
          #- packetbeat
          #- winlogbeat
          
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.12'

      - name: Install molecule
        run: pip3 install ansible molecule molecule-docker


      - name: Run molecule
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro.image }}
          MOLECULE_INSTANCE_NAME: ${{ matrix.distro.instance }}
          MOLECULE_BEATS_FLAVOR: ${{ matrix.beats_flavor }}